### ISSUE TITLE
Forked-systray & systrayhelper

### ISSUE THREAD

**Issue by sleeyax** [sungshon/PimpMyStremio#23]
I've challenged myself to get PimpMyStremio to work on an android device. I use termux with a chroot container running Ubuntu 19.04 for this. 

I can get all node modules to work except `forked-sytray`, because the post install script can't find any builds for my `ARM7` architecture. I used to solve this by installing `systrayhelper` manually, but this is not possible anymore because of [this commit](https://github.com/sungshon/forked-systray/commit/3b8c8faf000dadd3a28d7cc8125acb9f94f634ab) in your `forked-systray` fork.

I can 'patch' my way around this by modifying PimpMyStremio directly of course, but I'd like to avoid that as much as possible. 

What would be the best way to get around this? Or where you planning to fix 'copy from another location' eventually?

Thank you for this amazing piece of software :)

**Comment by sungshon** [comment]
lol, that's funny because that commit was the primary fix for `forked-systray` breaking on literally all other OS's :))

**Comment by sungshon** [comment]
This `systray` module has proven to be quite problematic, your issue should be easy enough to fix though, I'm guessing you're getting one of these errors:
https://github.com/sungshon/forked-systray/blob/master/scripts/fetch-prebuilt-helper.js#L43
https://github.com/sungshon/forked-systray/blob/master/scripts/fetch-prebuilt-helper.js#L47

I don't think these are legitimate errors to throw in a module post install script, as this project should work without `systray` too. So I'm thinking of just logging the errors instead of throwing them, and if systray is on an unsupported OS, it should export `false` or some dummy object, i'll check which option is cleanest.

I'll write up the code for it and test it out.

That's an insane (and awesome) thing you're doing there, I think Termux is even available for iOS, which means your solution might work on all mobile devices. Did you have any other issues while trying to run PimpMyStremio in Termux that I might be able to help with?

**Comment by sleeyax** [comment]
Well, I got some notes here: https://gist.github.com/sleeyax/e9635eb352a4fcdf94194f763d743689 - based on an older version of PimpMyStremio, when I just patched my way around `forked-systray` and `open` at the end. At the top is a `Known bugs` section.

But here are some more details:
1) Installing addons is working fine, but for some reason uninstalling them throws this error:
```
Uncaught Exception...
TypeError: Cannot read property '0' of null
    at process.on (/root/pmsandroid/src/lib/cleanUp.js:45:29)
    at process.emit (events.js:189:13)
    at process.emit (/root/pmsandroid/src/node_modules/source-map-support/source-map-support.js:474:21)
    at emitPromiseRejectionWarnings (internal/process/promises.js:119:20)
    at process._tickCallback (internal/process/next_tick.js:69:34)
```
However, addons are in fact  uninstalled even when this error is thrown. (When I refresh the webpage the layout is also updated correctly and indicates that it's not installed anymore)

2) Probably the biggest issue I'm having is that addons can't be installed on the mobile version of stremio. `Error occurred while adding addon` shows when I try to load from a specific addon manifest or catalog ( `stremio://127.0.0.1:7777/catalog.json` or `stremio://127.0.0.1:7777/<addon>/manifest.json`). Oddly enough, other devices on my LAN can install the addons using my private ip address. I've already tried entering the private ip address directly & enabling remote access, but both end up the same with the same result.

3) Also worth noting is that `open` and linux command `xdg-open` doesn't work in a headless environment like this. Currently PMS just logs an error w/o exiting, which is fine.
```
Error: spawn /root/.local/share/PimpMyStremio/assets/xdg-open ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by sungshon** [comment]
This is very useful info, as the more issues such as this that we fix in PMS, the easier it will be to install it on a much wider range of environments.

Do `phantomjs` and `youtube-dl` work though? Those also use binaries, but I guess the only way to test is with add-ons that use those modules..

**Comment by sleeyax** [comment]
IIRC, `youtube-dl` is no problem but `phantomjs` needs to be installed manually (which works fine)

& oh, really? I hope that's the issue! I was using an older version of stremio, then I went to check for updates in the playstore but it was gone, so I got the version from the site but then it came back to playstore AGAIN, and that's what I' running now. Ill check the link and make sure my version is the latest.

**Comment by sungshon** [comment]
I hope that's the issue, i know that no add-ons could be installed from PMS on android because of a bug, then it went off play store, came back and got fixed. Make sure to check thoroughly and uninstall all the other previous versions of Stremio you might have (there may be more then one) before installing this one, so u know that you're running the correct (latest) one.

**Comment by sungshon** [comment]
i'm guessing `phantomjs` needs to be installed manually because it doesn't support ARM, maybe i could fork it and add support for ARM in the postinstall script, then we could literally just release an ARM version of PMS :)

**Comment by sleeyax** [comment]
That would be awesome :P

& I just reinstalled stremio, it's now on the latest version `v1.2.11`. But still the same issue :/

**Comment by sungshon** [comment]
ok, i'll tend to the other issues and check it too afterwards, i have some android devices.

we at least know installing in the latest version of Stremio Android works, so it must be a PMS issue which should be easy to fix

**Comment by sungshon** [comment]
it's possible that i might have fixed the systray issue and issue #1 (but this fix just makes it show the real error, we still don't know where the promise rejection is)

can you test the `master` branch?

**Comment by sungshon** [comment]
and now possibly issue number 3.. as in PMS won't try to use `xdg-open` if it's not there

**Comment by sleeyax** [comment]
Can confirm that #3 is indeed no longer an issue.

#1 Uninstalling an addon now results in:
```
Add-on stopped: TheBeastLT/stremio-cdn-videos
AssertionError [ERR_ASSERTION]: rimraf: callback function required
    at rimraf (/root/PimpMyStremio-clean/src/node_modules/rimraf/rimraf.js:52:10)
    at onStopped (/root/PimpMyStremio-clean/src/lib/addon.js:388:5)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Uncaught Exception...
ReferenceError: repoName is not defined
    at process.on (/root/PimpMyStremio-clean/src/lib/cleanUp.js:50:36)
    at process.emit (events.js:189:13)
    at process.emit (/root/PimpMyStremio-clean/src/node_modules/source-map-support/source-map-support.js:474:21)
    at emitPromiseRejectionWarnings (internal/process/promises.js:119:20)
    at process._tickCallback (internal/process/next_tick.js:69:34)
```

**Comment by sungshon** [comment]
ok, it's possible i just fixed those 2 errors too, did not test though

**Comment by sungshon** [comment]
it looks like this is where we could add support for arm:
https://github.com/Medium/phantomjs/blob/master/lib/util.js#L91-L116

**Comment by sungshon** [comment]
which takes it's binaries from here:
https://github.com/Medium/phantomjs/releases/tag/v2.1.1

and supports setting a custom repo link as a process env variable for the binaries too, this shouldn't be hard, as long as we can find the binaries for arm 32bit / 64bit somewhere

**Comment by sleeyax** [comment]
> ok, it's possible i just fixed those 2 errors too, did not test though

It works :)

**Comment by sungshon** [comment]
ah, i see why `youtube-dl` works and `phantomjs` doesn't:

https://github.com/przemyslawpluta/node-youtube-dl/blob/master/lib/downloader.js#L16

It's using the same http endpoint for all platforms, and that endpoint redirects to the required binaries for your system, so the platform / architecture detection seems to be server side, as opposed to using `process.platform` and `process.arch`

**Comment by sungshon** [comment]
while i'm still working on getting PMS to install and work correctly on ARM, I had a thought about issue #2 (not being able to install add-ons on Android)

I think the issue is with `stremio://` and Android, in Stremio desktop and Web `stremio://` is replaced with `https:`, except for 127.0.0.1, where it is replaced with `http://`

I think Stremio Android does not have this exception, so it replaces `stremio://` with `https://` everywhere. Based on this assumption, i asked bamboogod if he has any way of contacting Stremio about it. He did manage to contact them, and they confirmed that this exception is not done for Android, but will be added in the next release.

This still does not explain why remote doesn't work on Android, I'll need to look into that, it might be something simple.

**Comment by sleeyax** [comment]
Ahh, I knew it had something to do with https... there was just no way to know for sure because Stremio android & desktop clients are not open source AFAIK, but I'm glad it's confirmed now. Thanks for your time!

**Comment by sleeyax** [comment]
I just checked and remote is working fine with the latest version of PMS. I must have made a mistake while testing with the older version, so we can scrap that issue off our list :)

**Comment by sungshon** [comment]
Yeah, I couldn't see any reason why remote wouldn't work.. But we still need to wait for Stremio Android to update with the fix for it to work locally. Remote is highly inefficient, as it uses a reverse proxy.

When they do release it, I think that will be the last thing we can fix. I did test adding arm version to the phantomjs module build. But phantomjs also has other dependencies for arm that are missing if we install it like that.

So I just made it do a soft error if the platform is incompatible. Users can either install it with `apt` like you did, or we could build PMS on arm, and create a `.deb` that installs the `phantomjs` dependency too. Building for arm should work, but we might need a device with a specific arm version for each build..

`phantomjs` and installing on android without remote are the last 2 things for this, i think. And as wrote before, I stopped trying to get `phantomjs` to just auto-install for the moment.

Now, if `youtube-dl` would also give a soft error too if the platform is incompatible, that might even allow PMS to run in stranger scenarios, like inside [Dory.js](https://play.google.com/store/apps/details?id=io.tempage.dorynode&hl=en). Although the binaries for youtube-dl and phantomjs would be missing in this scenario, and those features would just not work in add-ons, that would still leave some add-ons working that don't need them at all, and installation in `Dory.js` would be stupid easy.

These are my current thought on everything related to this, just bringing you up to speed. :)

**Comment by sungshon** [comment]
I think the android app should be updated now, and should work with PMS installed on the android device.

But I think it was removed from the app store again, so it's probably available only on their site now.

I haven't tested it though.

**Comment by sleeyax** [comment]
I just checked and PMS does indeed run on android without any issues now! 

I'll see if [my guide](https://gist.github.com/sleeyax/e9635eb352a4fcdf94194f763d743689) needs any updates, but other than that I think this issue can be closed :)

**Comment by sungshon** [comment]
Keep in mind that missing binaries will now cause soft errors, instead of breaking `npm install`.

I'll make a new update soon too, because some add-ons needed some new whitelisted modules, so the next release will fix a few add-ons that have broken down in the meanwhile. I think one new add-on might be added to this new release too.
