### ISSUE TITLE
how can i install on win7 32bit?

### ISSUE THREAD

**Issue by rrosajp** [sungshon/PimpMyStremio#25]
@sungshon 
hi i like to try this addon but don't know how to install i did dl but it give me error.
ver of this file in not compatible with ver of window you r running ,btw mine is win 7 32bit.
thanks for any help.

**Comment by sungshon** [comment]
Hi, srry for the late reply, i only built PimpMyStremio for 64bit on all OS's.

A 32bit build should work for you, I should make a release anyway, I'll look into adding a Windows 32bit version too.

**Comment by rrosajp** [comment]
@sungshon 
thanks, i did try to install but did not work . i appreciate yr help.

**Comment by sungshon** [comment]
I've just released PimpMyStremio v1.1.7:
https://github.com/sungshon/PimpMyStremio/releases

For Windows 32bit you'll need to download "PimpMyStremio-win-x86.zip"

You mentioned that you want to "try this addon", keep in mind though, this is not an add-on, this is a Local Add-on Manager, this means it's a separate application that hosts 29 Stremio add-ons that you can't find anywhere else.

And due to the nature of PimpMyStremio local add-ons, most of these add-ons won't even need Stremio itself installed, as they will also work just fine in Stremio Web, as long as PimpMyStremio is running.

Another thing to note is that when you close PimpMyStremio, it stops all it's add-ons too, as it needs to be running for the add-ons to work.
