### ISSUE TITLE
Stop using serveo.net for remote access

### ISSUE THREAD

**Issue by vilp** [sungshon/PimpMyStremio#44]
It has been down for the past 2 day and up for a couple minutes/hours then is down. Right now it is down.

I found some alternative on a Reddit post https://www.reddit.com/r/webdev/comments/ca634r/-/et61ukj

**Comment by sungshon** [comment]
That's pretty sad, we've also tried Localtunnel (it's in that list) in the past, but the connection was unstable compared to Serveo.

I'll see if any others work fairly well, and probably also make it a dropdown to pick the reverse proxy service you wish to use..

**Comment by sungshon** [comment]
Also, based on the comments from this post:

https://www.reddit.com/r/Stremio/comments/dl90sv/allow_us_to_install_addons_from_remote_servers_on/

I'm expecting that there is also a solution for this problem that the Stremio team is working on.

**Comment by sezgit** [comment]
Alright I'm trying to find some solution rn until stremio fixes the problem

**Comment by sezgit** [comment]
localhost.run works, problem is you need to reinstall every time due to the new domain(correct me if you can change it). However it's pretty good with my 1GB ram VPS

**Comment by sungshon** [comment]
localhost.run doesn't seem to support custom subdomains, i tried using it with serveo's pattern of setting a subdomain and it didn't work, also there's no documentation for any features at all on localhost.run, which makes me think that how you use it now is the full extent of that service.

Unfortunately, without custom subdomain support it can't be added to this project.

I've been going through a bunch of possible options:

https://sshreach.me/ (not free, so not an option)
http://ultrahook.com/ (self-signed ssl certificate, so not an option)
https://holepunch.io/ (would require users to make their own accounts for it, also bandwidth is limited)
https://ngrok.com/ (would also require users to make their own accounts for it)
https://ssi.sh/ (source seems available, but it doesn't seem to work for some reason)
http://localhost.run/ (does not support custom subdomains)

After going through all of these, Localtunnel and Serveo still seem like the only options. And due to the fact that PimpMyStremio needs to proxy some add-on's videos internally in order to get them working, any reverse proxy service will still get crushed under the presumable bandwidth needs of PimpMyStremio users.

I'm expecting the Stremio team solution to involve wildcard ssl certificates, in which case no reverse proxies will be needed anymore, but users would need to do port forwarding in their routers and setup their firewalls with such a solution if they want them working online.

Maybe some holepunching logic could be added as well to open the port to the web to avoid the need to do port forwarding, but that can't be expected to work in all cases like reverse proxies would.

The only thing I can do for now is make a select box that allows choosing between Localtunnel and Serveo, but as I mentioned before, Localtunnel has been used in the past and it seemed to disconnect randomly from their service.

**Comment by sezgit** [comment]
ssi.sh is open source which you said, but doesn't work for some reason is what I'm confused? Did you try it already?

I'm thinking of buying those cheap 79 cents .XYZ domain that epik.com does time to time then get those ServerCheap.net or buyvm vps to host, usually costs 2 bucks per month.

**Comment by sungshon** [comment]
> ssi.sh is open source which you said, but doesn't work for some reason is what I'm confused? Did you try it already?

It's open source, and they also deployed the project to "ssi.sh", i tried using their deployed version and it doesn't work for some reason.

> I'm thinking of buying those cheap 79 cents .XYZ domain

You can also get free domains from http://my.ga/ , but they expire in a year and may even be randomly removed by them. But you can try one for tests to not spend money on a domain, then connect that to Cloudflare to add free SSL and then to whatever hosting / deployment option where PimpMyStremio is, or alternatively just host a reverse proxy yourself from the above options and use that to give SSL to PimpMyStremio.

Both solutions would work, the only reason why PimpMyStremio doesn't work remotely in Stremio is because all add-ons need to have SSL for Stremio to load them.

**Comment by sezgit** [comment]
Serveo is down for phishing but https://jerrington.me/posts/2019-01-29-self-hosted-ngrok.html works, step one is only needed to do. Worked on a domain

**Comment by sezgit** [comment]
i have seen a lot of plugin use now.sh, maybe that's an addon to a suggestion

**Comment by sungshon** [comment]
I've been thinking lately that maybe I've gone about this all wrong..

While I was making support for various reverse proxies directly in PMS, I just started pondering the idea of such remote connection solutions be made as add-ons themselves.

I could remove the remote connection code completely, and create an add-on for Serveo, another for LocalTunnel, and lately I've also been looking at: https://www.duckdns.org/

When a problem reaches this level of complexity, it's usually best to move it away from the primary code and into the add-on developers' hands. This makes sense because the solution is actually having many more choices then the one we're currently using.

**Comment by lfvideos** [comment]
> 
> 
> Also, based on the comments from this post:
> 
> https://www.reddit.com/r/Stremio/comments/dl90sv/allow_us_to_install_addons_from_remote_servers_on/
> 
> I'm expecting that there is also a solution for this problem that the Stremio team is working on.

Hey, thast my post on reddit! im glad you saw it but im afraid its really hard to trust what they say because i've asked for a few features and they always say they are working on it but i've never seen a single one of them put on the main program (things like being able to change the audio languaje or enabling/disabling embedded subtitles)   so i would take it with a grain of salt. 

I think your aproach of adding them as addons could be the solution to it but its outside of my knowledge. If you need us to test anything i can be your guinea pig

**Comment by sungshon** [comment]
I think for them (and me, and developers in general), it's more of a thing of time and priorities, they might indeed want to implement everything, but time is nobody's friend. :))

BTW, changing audio tracks works for me in the current Desktop version of Stremio.

I'm going to close this issue in favor of the better explained issue at:
https://github.com/sungshon/PimpMyStremio/issues/53

**Comment by sungshon** [comment]
I've removed the "access remotely" feature completely for the moment, as more users started having issues with it. It will not be available in the next release.

**Comment by sungshon** [comment]
The next release of PimpMyStremio will have a setting that will allow the addons to work in Stremio through LAN.
