### ISSUE TITLE
[OSX Error] “PimpMyStremio” is damaged and can’t be opened. You should move it to the Trash.

### ISSUE THREAD

**Issue by jaypeewin** [sungshon/PimpMyStremio#46]
Hi, 

I was having an issue with one of the addons for pms. I tried deleting pms and reinstalling it but receive this error when opening it again. "“PimpMyStremio” is damaged and can’t be opened. You should move it to the Trash."

on MacOS Catalina

**Comment by sungshon** [comment]
It's possible that the update failed for some reason and the engine is now a corrupted.

When downloading PimpMyStremio, you are actually downloading an updater, which checks for a new version, downloads it and installs it if needed, then runs PimpMyStremio.

The actual installed version is at `~/Library/Preferences/PimpMyStremio`, deleting this folder deletes the entirety of all PimpMyStremio data from your Desktop.

You should try deleting that folder and re-downloading PimpMyStremio.

**Comment by sungshon** [comment]
Actually, no.. i don't think an update caused this, any chance you can tell me what add-on you were you having issues with? I should debug it to make sure it isn't causing any issues for the PimpMyStremio environment.

**Comment by jaypeewin** [comment]
I tried deleting that folder but am still receiving the same error. I was having issues with the Jackett addon. I was never able to load it onto Stremio.

**Comment by jaypeewin** [comment]
Do you think it could be an issue with terminal using zsh on CatalinaOS instead of bash?

**Comment by jaypeewin** [comment]
I was also able to install the 123TV add-on to stremio but it didn't work.

**Comment by sungshon** [comment]
Uhm, I haven't personally tested it on Catalina.. You should try running PimpMyStremio with `--verbose` from the terminal to see if there's anything helpful in the logs. (they will be printed in the terminal)

A different user recently mentioned he managed to get Jackett working well with that add-on by using the mono version of Jackett:
https://github.com/sungshon/PimpMyStremio/issues/45

**Comment by jaypeewin** [comment]
Nov  7 19:10:09 Mac-mini com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x10000004.PimpMyStremio[1466]): Service exited due to SIGKILL | sent by CoreServicesUIAgent[1462]

I could not get it to run in terminal. I see this error in the console.app. Do you know what it means?

**Comment by sungshon** [comment]
This does not tell us much...

You can also try running it from the terminal with the `--no-children` flag, to see if that helps, but I somehow doubt it.

I've checked around to see if there were any major changes in Catalina, but the only one I can find is that it now only supports 64bit apps, but PimpMyStremio was always 64bit on OSX, so that can't be the problem.

**Comment by sungshon** [comment]
Oh, ok, I think I see the problem now, check this StackExchange answer:
https://apple.stackexchange.com/questions/372084/macos-catalina-app-is-damaged-and-cant-be-opened-you-should-move-it-to-the-t

Please try the solution mentioned there. As much as I can gather from it, some OSX security thing is much more rigorous in Catalina, and PimpMyStremio was quarantined without asking you, OSX is now actively blocking it from starting.

This is probably due to the fact that I'm not paying for a very expensive code signing certificate to sign the app, which would make OSX / Win trust it in general.

**Comment by sungshon** [comment]
Yup, this is an OSX Gatekeeper issue, there are more solutions on this page too:

https://apple.stackexchange.com/questions/262355/xxx-cant-be-opened-you-should-move-it-to-trash-for-flash-projector-applicat

This is more of an OSX issue in general it seems, not a PimpMyStremio issue.

**Comment by jaypeewin** [comment]
That was the issue. I tried the first solution and it worked.

Thank you so much for your help on this issue and thank you for all your great work on PimpMyStremio.

**Comment by sungshon** [comment]
Glad to hear it! For add-ons that don't currently work, they could be automatically fixed in time as their developers fix them. All installed add-ons are automatically updated when you start PimpMyStremio.
