### ISSUE TITLE
PMS doesn't work on LAN

### ISSUE THREAD

**Issue by ikarusnc** [sungshon/PimpMyStremio#54]
Hi, PMS and all my stremio apps are at latest version. I can download and start addons on PMS server but I fail to install them on stremio on windows it tells me "ERR_OPENING_MEDIA" and "failed to fetch".

**Comment by sungshon** [comment]
PMS can only work locally, this is because Stremio needs SSL to work, even from LAN, the only exception is the local IP.

There are better solutions for this in the works, but right now the only (and not very good) workaround is to enable "Access remotely" in the settings, which will use a reverse proxy to give SSL enabled links that Stremio will support.

**Comment by chicungunya** [comment]
> PMS can only work locally, this is because Stremio needs SSL to work, even from LAN, the only exception is the local IP.
> 
> There are better solutions for this in the works, but right now the only (and not very good) workaround is to enable "Access remotely" in the settings, which will use a reverse proxy to give SSL enabled links that Stremio will support.

Hello @sungshon , I followed this tutorial for Access Remotely : https://github.com/sungshon/PimpMyStremio/blob/master/docs/user-guide.md

BUT, when I click on "Access remotely", I choose a server password ans click on "Save and restart", nothing is happening. I have only a new local adress which is http://127.0.0.1:7777/login.html.
I don't have any remote URL.
Can you please help?
Thank you

**Comment by sungshon** [comment]
Stremio needs a HTTPS url to work, HTTP urls will only work locally with it. For the "Access Remotely" feature we use serveo.net, which is a reverse proxy, and by far not the best choice.

Other users have reported serveo.net not working before too:
https://github.com/sungshon/PimpMyStremio/issues/44

It is far from the best choice.. I have a RPI 3B+ that works great through HTTPS externally using DuckDNS and Let's Encrypt, which are free to use and give a free subdomain + HTTPS, but does require setting up port forwarding in the router..

I'm thinking of removing the access remotely feature completely.. and just point to some guide that explains how to manually setup a HTTPS server on a device.

And maybe in time I'll make the "Networking addons" feature:
https://github.com/sungshon/PimpMyStremio/issues/53

Which would handle this need better.

**Comment by chicungunya** [comment]
> Stremio needs a HTTPS url to work, HTTP urls will only work locally with it. For the "Access Remotely" feature we use serveo.net, which is a reverse proxy, and by far not the best choice.
> 
> Other users have reported serveo.net not working before too: #44
> 
> It is far from the best choice.. I have a RPI 3B+ that works great through HTTPS externally using DuckDNS and Let's Encrypt, which are free to use and give a free subdomain + HTTPS, but does require setting up port forwarding in the router..
> 
> I'm thinking of removing the access remotely feature completely.. and just point to some guide that explains how to manually setup a HTTPS server on a device.
> 
> And maybe in time I'll make the "Networking addons" feature: #53
> 
> Which would handle this need better.

Thanks for your answer, I will wait PMS on Android because i'm not too techie.
Let me know when it will be released. And thanks a lot for your work

**Comment by sungshon** [comment]
There is no simple example for this. In order for PMS to work remotely with Stremio it needs a domain and a SSL certificate for that domain.

In order for a local server to have a domain and a SSL certificate, there are multiple options:
- reverse proxies, which presume that you are not using your server directly, but a different server that already has a domain and a SSL certificate, that proxies all the requests to your server and back, this is by far the worst solution, but the easiest solution and what we used in PMS (but works horribly all does not work at all)
- actually get a domain and SSL certificate, which presume that your local server is contacted directly (works flawlessly but there are no clear simple solutions for getting this done for free)

This is not a PMS problem, Stremio requests these things in order to communicate remotely. ANY local server that would need a domain and a SSL certificate would need to solve this in it's own way.

The ONLY solution I've ever seen that works well with a fully free domain (be it subdomain, it does not matter) and a fully free SSL certificate is by using DuckDNS and Let's Encrypt.

I do not know of any application that you could just press a few buttons and get these benefits, nor do I know of a simple way of doing it. In my case with the RPI 3B+, I have Hass.io installed on it, and there is an addon in Hass.io that handles all of this for their local server with DuckDNS and Let's Encrypt.

If I just had some magical solution for you, I would of said it already. But there is no magical solution, you can google for a ton of articles and possible solutions for this, it's not specific to PMS in any way.

**Comment by chicungunya** [comment]
Thank your for this detailed answer. I'm not enough techie to keep going so. I will wait PMS on Android to use Jackett for Stremio (because in face I only need Jackett)
Let me know when I could do that. Thanks a lot for your work

**Comment by sungshon** [comment]
@chicungunya I'll try to keep u updated with the progress

**Comment by sungshon** [comment]
The next release of PimpMyStremio will have a setting that will allow the addons to work in Stremio through LAN.

So I'm closing this for now.

**Comment by chicungunya** [comment]
Hello @sungshon 
I finally installed PMS and Jackett on my Raspberry Pi and put them on a Duck DNS adress with SSL certificate.
I installed  on my Android TV 
But Stremio find no result with Jackett

PMS is in LAN config
Do I have to use it in WAN config ? 

Where is my mistake ? 

Thanks a lot
