### ISSUE TITLE
PMS stuck at download

### ISSUE THREAD

**Issue by Shinzawaii** [sungshon/PimpMyStremio#55]
So when I DL and run the latest pms.exe from github it does say there's an update, automatically opens my browser and starts dl'ing. In brave browser it stays stuck on keep downloading, if I change my default browser it will say download complete, you can now close this window... only to give me the same message when I open the .exe no local login page whatsoever.

What seems to be the problem? Browser choice?

**Comment by sungshon** [comment]
It's hard to say what the problem is, but even if the browser would have an issue with the updater page, it will still download the update, and run it, then start PMS in a new browser tab. The updater page itself just polls for what text to show on the page, nothing else.

In order to get more info on this, please run PimpMyStremio from the command line with the `--verbose` flag. This will make the app show all it's logs in the command line, so we can clearly see what's going on.

**Comment by Shinzawaii** [comment]
Seems to work now... it loads the local page. Can't say what caused the original issue.
