### ISSUE TITLE
PMS does not open browser page anymore

### ISSUE THREAD

**Issue by CreativeDad** [sungshon/PimpMyStremio#58]
Its seems after last update the launcher does not open the browser page anymore so adding new addons can't be achieved

**Comment by sungshon** [comment]
The way it works now is that it must first start all addons you've installed, after which it starts the web server and loads the page in your browser.

When I first created this project, I thought that logic was solid enough, as there are timeouts set to each addon initialization and other safe guards against addon failure. But then I opted to running each addon in it's own dedicated process, this adds many benefits but also increases the time it takes to initialize each addon, thus making startup of the web server increase in load time too. With as many addons as there are now, this can really become a problem.

Recently, I've been experimenting with changing this logic in order to start the web server first, then open the browser page, and finally loading the addons afterwards, which should fix this issue forever, hopefully..

As for your current issue, there are 2 choices:
- you start PimpMyStremio from the terminal with the `--verbose` flag in order to see the logs, and we can hopefully identify the issue
- you delete your user data by deleting the directory from one of the paths:
Win: `%AppData%/PimpMyStremio`
OSX: `~/Library/Preferences/PimpMyStremio`
Linux: `~/.local/share/PimpMyStremio`
(deleting this directory will remove all your user defined data, so starting PimpMyStremio again after this will re-download the latest version and act like you are a new user with no addons installed)

**Comment by CreativeDad** [comment]
Wow yeah deleting the data in the folder worked a treat got the update and the choice of addons again thanks!

**Comment by sungshon** [comment]
Nobody ever wants to use `--verbose` to debug :))

**Comment by CreativeDad** [comment]
I would happily use it if i knew how to
