### ISSUE TITLE
It doesn't open the browser window

### ISSUE THREAD

**Issue by Jedah85** [sungshon/PimpMyStremio#65]
Hello,
The first time I used this, everything worked perfectly, but for a reason I don't understand it doesn't work anymore. When I execute the program, it opens a cmd window that says everything is ok and up to date, but it doesn't open the browser tab making it impossible to chose addons or change setings. 
I checked my PC processes on "Process Lasso" and it shows multiple "engine.exe" processes with a green icon and I guesses that was related to PMS, if I wait a few second the process starts to reproduce itself until there are 12 of them but nothing happens. My guess is that it tries to open the broser but can't for a reason and it creates a new process to try again.
I tried running the software as an Administrator with the same results. My default Browser is Chrome  v80.0.3987.
What could be causing this issue? Could you give me the URL to the browser page that lets you chose the addons or is it different for each usser? I hope you can help me, and thank you for the amazing app, for the short time I was able to use, I loved it

**Comment by sungshon** [comment]
There is a quick solution here: https://github.com/sungshon/PimpMyStremio/issues/58

Nobody ever wants to debug the issues, so I have no idea what's breaking it for some users.

I suspect it may be caused by the removal of the "RARBG 4K" addon, or maybe by the Serveo remote access implementation.

You're right in saying `engine.exe` is from PMS, it's normal for it to "reproduce" itself. Because it runs every addon in it's own process, and every addon's process will also show as `engine.exe` in your process list.

I'm making a new release today that will hopefully resolve some user confusion, as it will open a page with a loader saying exactly what PMS is doing when it's starting up.

**Comment by sungshon** [comment]
I've released the new version, I also recommend downloading the new launcher from here:
https://github.com/sungshon/PimpMyStremio/releases

As this release adds some new features to the launcher too.

**Comment by Jedah85** [comment]
I tried to debug it, but am using Windows and can't make the "verbose" command work. I tried many variations (--verbose, -verbose, /verbose) with different spaces but none of them did anything.
Anyway, I deleted the user data folder and downloaded the new version and works like a charm! Thank you, that was fast

**Comment by sungshon** [comment]
I finally found a user that was willing to debug and he gave up 😆 

For future reference, you would of needed to open a command line window, then go to the same folder where the PimpMyStremio launcher was, and type:
`PimpMyStremio.exe --verbose`

This would of opened PimpMyStremio and the logs should of been visible in the command line window that you opened it with.
