### ISSUE TITLE
Android : Load in stremio app not working

### ISSUE THREAD

**Issue by chicungunya** [sungshon/PimpMyStremio#74]
Hello,
I ve installed PMS on my Android TV with this guide : https://gist.github.com/sleeyax/e9635eb352a4fcdf94194f763d743689
Everything is working but when I try to load in app it does not work. 
When I load in web, it works, I can see my apps, can install it but I have nothing on my app.
Can you help please ? :)
Thanks a lot !

**Comment by chicungunya** [comment]
Edit : I copy past http://127.0.0.1:7777/stremio-jackett-local/manifest.json on addon url in my stremio app android and it works. I can install Jackett.
BUT, Jackett seems to not work because i don't find any results from my trackers

**Comment by sungshon** [comment]
This is more on an addon issue then a PMS issues. But Jackett works afaik, so it could even just be a Stremio Android issue.. (although i kind of doubt it's a Stremio issue)

Where are you running the Jackett app though? Did you set the URL to the Jackett app correctly in the Jackett addon's settings? And also the correct API KEY in the settings?

**Comment by chicungunya** [comment]
It's ok it works but it depends of links. Jackett and PMS are working both on my android TV
Even if there is a lot of seeders, some links doesn't work. Why?
Maybe a problem of cache ? I don't know. Thanks for your help

**Comment by danamag** [comment]
@chicungunya maybe check the comment from the jackett developer at this reddit post:
https://www.reddit.com/r/StremioAddons/comments/fvurek/jackett_addon_streams_not_loading/

**Comment by chicungunya** [comment]
Thank you ! I ll ask ! You can close the ticket !
About Android version do you know when a first version will be out ?

**Comment by sungshon** [comment]
@chicungunya If you mean an android version for PMS.. Although I made some significant progress, I'm considering dropping it..

This is because:
1. it can't ever have the full abilities of the desktop app
2. there are many android vendors that kill background apps randomly: https://dontkillmyapp.com/

As PMS would be a background app, and it needs to be running in order to work, then it might not be worth the effort.

The guide of getting it working with Termux though would have the full abilities of PMS, so there's already a plus to using that method over an Android version.

I'm thinking more of maybe making a Raspberry Pi version, not sure yet..

**Comment by sungshon** [comment]
I'm presuming this resolved and closing the issue
